[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@ampproject/toolbox-optimizer"]
  included_files = ["**/*.node"]
  node_bundler = "esbuild"
  
# Increase timeout for functions to accommodate API calls
[functions."*"]
  timeout = 60

# Force Next.js SSR to work properly
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 