[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

# Set longer timeout for all functions
[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/openai/**"]

# Set a higher timeout specifically for content generation
[functions.content-generate]
  included_files = ["node_modules/openai/**"]
  node_bundler = "esbuild"
  timeout = 26

# Set a higher timeout for keyword extraction
[functions.keywords-extract]
  included_files = ["node_modules/openai/**"]
  node_bundler = "esbuild"
  timeout = 20

# Set a higher timeout for more keywords generation
[functions.keywords-more]
  included_files = ["node_modules/openai/**"]
  node_bundler = "esbuild"
  timeout = 20

# Set a higher timeout for the diagnostic tool
[functions.tools-diagnostic]
  included_files = ["node_modules/openai/**"]
  node_bundler = "esbuild"
  timeout = 26

# Set a higher timeout for the keyword metrics tool
[functions.tools-keyword-metrics]
  included_files = ["node_modules/openai/**"]
  node_bundler = "esbuild"
  timeout = 15

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the problematic redirects that are interfering with Next.js asset loading
# and replace with standard Next.js handling

# Default SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 